[package]
name = "mastering-rust-tutorial"
version = "0.1.0"
authors = ["Massimiliano Sartoretto <massimiliano.sartoretto@movingimage.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
